apiVersion: apps/v1
kind: Deployment
metadata:
  name: jige-bot
  namespace: bot
  labels:
    app: jige-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jige-bot
  template:
    metadata:
      name: jige-bot
      labels:
        app: jige-bot
    spec:
      containers:
        - name: jige-bot
          image: 'jige_bot:latest'
#          imagePullPolicy: Never
          ports:
            - containerPort: 32080
              protocol: TCP
          env:
            - name: DEPLOYMENT_ENV
              value: prod
            - name: SUPERUSERS
              value: '{}'
            - name: COMMADN_START
              value: "{'', '/', '!', '／', '！'}"
            - name: SESSION_RUN_TIMEOUT
              value: '20'
            - name: REQUEST_FRIEND_COMMENT_PASSWD
              value: jigewudi