kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cqhttp
  namespace: bot
  labels:
    pvc: cqhttp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath
