apiVersion: v1
kind: Service
metadata:
  name: cqhttp-vnc
  namespace: bot
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 32090
  selector:
    app: cqhttp
---
apiVersion: v1
kind: Service
metadata:
  name: cqhttp-ws
  namespace: bot
spec:
  type: NodePort
  ports:
    - port: 6700
      nodePort: 32067
  selector:
    app: cqhttp
---
apiVersion: v1
kind: Service
metadata:
  name: jige-ws
  namespace: bot
spec:
  ports:
    - port: 32080
      targetPort: 32080
  selector:
    app: jige-bot